// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncProfile int32

const (
	EncProfile_PROFILE_V1 EncProfile = 0
	EncProfile_PROFILE_V2 EncProfile = 1
	EncProfile_PROFILE_V3 EncProfile = 2
)

// Enum value maps for EncProfile.
var (
	EncProfile_name = map[int32]string{
		0: "PROFILE_V1",
		1: "PROFILE_V2",
		2: "PROFILE_V3",
	}
	EncProfile_value = map[string]int32{
		"PROFILE_V1": 0,
		"PROFILE_V2": 1,
		"PROFILE_V3": 2,
	}
)

func (x EncProfile) Enum() *EncProfile {
	p := new(EncProfile)
	*p = x
	return p
}

func (x EncProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_storage_storage_proto_enumTypes[0].Descriptor()
}

func (EncProfile) Type() protoreflect.EnumType {
	return &file_internal_proto_storage_storage_proto_enumTypes[0]
}

func (x EncProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ListDataBlocksRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientId    *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListDataBlocksRequest) Reset() {
	*x = ListDataBlocksRequest{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataBlocksRequest) ProtoMessage() {}

func (x *ListDataBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListDataBlocksRequest) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *ListDataBlocksRequest) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListDataBlocksRequest) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListDataBlocksRequest) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClientId = nil
}

type ListDataBlocksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ClientId *string
}

func (b0 ListDataBlocksRequest_builder) Build() *ListDataBlocksRequest {
	m0 := &ListDataBlocksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ClientId = b.ClientId
	}
	return m0
}

type DataBlock struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockId     int32                  `protobuf:"varint,1,opt,name=block_id,json=blockId"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Chiphertext []byte                 `protobuf:"bytes,3,opt,name=chiphertext"`
	xxx_hidden_Salt        []byte                 `protobuf:"bytes,4,opt,name=salt"`
	xxx_hidden_Nonce       []byte                 `protobuf:"bytes,5,opt,name=nonce"`
	xxx_hidden_Profile     EncProfile             `protobuf:"varint,6,opt,name=profile,enum=storage.EncProfile"`
	xxx_hidden_Type        *BlockType             `protobuf:"bytes,7,opt,name=type"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataBlock) Reset() {
	*x = DataBlock{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock) ProtoMessage() {}

func (x *DataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataBlock) GetBlockId() int32 {
	if x != nil {
		return x.xxx_hidden_BlockId
	}
	return 0
}

func (x *DataBlock) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *DataBlock) GetChiphertext() []byte {
	if x != nil {
		return x.xxx_hidden_Chiphertext
	}
	return nil
}

func (x *DataBlock) GetSalt() []byte {
	if x != nil {
		return x.xxx_hidden_Salt
	}
	return nil
}

func (x *DataBlock) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *DataBlock) GetProfile() EncProfile {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_Profile
		}
	}
	return EncProfile_PROFILE_V1
}

func (x *DataBlock) GetType() *BlockType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return nil
}

func (x *DataBlock) SetBlockId(v int32) {
	x.xxx_hidden_BlockId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *DataBlock) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *DataBlock) SetChiphertext(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chiphertext = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *DataBlock) SetSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Salt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *DataBlock) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *DataBlock) SetProfile(v EncProfile) {
	x.xxx_hidden_Profile = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *DataBlock) SetType(v *BlockType) {
	x.xxx_hidden_Type = v
}

func (x *DataBlock) HasBlockId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataBlock) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataBlock) HasChiphertext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DataBlock) HasSalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DataBlock) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DataBlock) HasProfile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DataBlock) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *DataBlock) ClearBlockId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BlockId = 0
}

func (x *DataBlock) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *DataBlock) ClearChiphertext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Chiphertext = nil
}

func (x *DataBlock) ClearSalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Salt = nil
}

func (x *DataBlock) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Nonce = nil
}

func (x *DataBlock) ClearProfile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Profile = EncProfile_PROFILE_V1
}

func (x *DataBlock) ClearType() {
	x.xxx_hidden_Type = nil
}

type DataBlock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockId     *int32
	Title       *string
	Chiphertext []byte
	Salt        []byte
	Nonce       []byte
	Profile     *EncProfile
	Type        *BlockType
}

func (b0 DataBlock_builder) Build() *DataBlock {
	m0 := &DataBlock{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BlockId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_BlockId = *b.BlockId
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Title = b.Title
	}
	if b.Chiphertext != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Chiphertext = b.Chiphertext
	}
	if b.Salt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Salt = b.Salt
	}
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Nonce = b.Nonce
	}
	if b.Profile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Profile = *b.Profile
	}
	x.xxx_hidden_Type = b.Type
	return m0
}

type SaveDataBlockRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Chiphertext []byte                 `protobuf:"bytes,2,opt,name=chiphertext"`
	xxx_hidden_Salt        []byte                 `protobuf:"bytes,3,opt,name=salt"`
	xxx_hidden_Nonce       []byte                 `protobuf:"bytes,4,opt,name=nonce"`
	xxx_hidden_Profile     EncProfile             `protobuf:"varint,5,opt,name=profile,enum=storage.EncProfile"`
	xxx_hidden_TypeId      int32                  `protobuf:"varint,6,opt,name=type_id,json=typeId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SaveDataBlockRequest) Reset() {
	*x = SaveDataBlockRequest{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDataBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDataBlockRequest) ProtoMessage() {}

func (x *SaveDataBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveDataBlockRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *SaveDataBlockRequest) GetChiphertext() []byte {
	if x != nil {
		return x.xxx_hidden_Chiphertext
	}
	return nil
}

func (x *SaveDataBlockRequest) GetSalt() []byte {
	if x != nil {
		return x.xxx_hidden_Salt
	}
	return nil
}

func (x *SaveDataBlockRequest) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *SaveDataBlockRequest) GetProfile() EncProfile {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Profile
		}
	}
	return EncProfile_PROFILE_V1
}

func (x *SaveDataBlockRequest) GetTypeId() int32 {
	if x != nil {
		return x.xxx_hidden_TypeId
	}
	return 0
}

func (x *SaveDataBlockRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *SaveDataBlockRequest) SetChiphertext(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chiphertext = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *SaveDataBlockRequest) SetSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Salt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *SaveDataBlockRequest) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *SaveDataBlockRequest) SetProfile(v EncProfile) {
	x.xxx_hidden_Profile = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *SaveDataBlockRequest) SetTypeId(v int32) {
	x.xxx_hidden_TypeId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *SaveDataBlockRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SaveDataBlockRequest) HasChiphertext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SaveDataBlockRequest) HasSalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SaveDataBlockRequest) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SaveDataBlockRequest) HasProfile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SaveDataBlockRequest) HasTypeId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SaveDataBlockRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *SaveDataBlockRequest) ClearChiphertext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Chiphertext = nil
}

func (x *SaveDataBlockRequest) ClearSalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Salt = nil
}

func (x *SaveDataBlockRequest) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Nonce = nil
}

func (x *SaveDataBlockRequest) ClearProfile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Profile = EncProfile_PROFILE_V1
}

func (x *SaveDataBlockRequest) ClearTypeId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TypeId = 0
}

type SaveDataBlockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Chiphertext []byte
	Salt        []byte
	Nonce       []byte
	Profile     *EncProfile
	TypeId      *int32
}

func (b0 SaveDataBlockRequest_builder) Build() *SaveDataBlockRequest {
	m0 := &SaveDataBlockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Title = b.Title
	}
	if b.Chiphertext != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Chiphertext = b.Chiphertext
	}
	if b.Salt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Salt = b.Salt
	}
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Nonce = b.Nonce
	}
	if b.Profile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Profile = *b.Profile
	}
	if b.TypeId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_TypeId = *b.TypeId
	}
	return m0
}

type SaveDataBlockResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDataBlockResponse) Reset() {
	*x = SaveDataBlockResponse{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDataBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDataBlockResponse) ProtoMessage() {}

func (x *SaveDataBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SaveDataBlockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SaveDataBlockResponse_builder) Build() *SaveDataBlockResponse {
	m0 := &SaveDataBlockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListDataBlocksResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DataBlocks *[]*DataBlock          `protobuf:"bytes,1,rep,name=data_blocks,json=dataBlocks"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListDataBlocksResponse) Reset() {
	*x = ListDataBlocksResponse{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataBlocksResponse) ProtoMessage() {}

func (x *ListDataBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListDataBlocksResponse) GetDataBlocks() []*DataBlock {
	if x != nil {
		if x.xxx_hidden_DataBlocks != nil {
			return *x.xxx_hidden_DataBlocks
		}
	}
	return nil
}

func (x *ListDataBlocksResponse) SetDataBlocks(v []*DataBlock) {
	x.xxx_hidden_DataBlocks = &v
}

type ListDataBlocksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DataBlocks []*DataBlock
}

func (b0 ListDataBlocksResponse_builder) Build() *ListDataBlocksResponse {
	m0 := &ListDataBlocksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DataBlocks = &b.DataBlocks
	return m0
}

type BlockType struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_TypeName    *string                `protobuf:"bytes,2,opt,name=type_name,json=typeName"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BlockType) Reset() {
	*x = BlockType{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockType) ProtoMessage() {}

func (x *BlockType) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlockType) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *BlockType) GetTypeName() string {
	if x != nil {
		if x.xxx_hidden_TypeName != nil {
			return *x.xxx_hidden_TypeName
		}
		return ""
	}
	return ""
}

func (x *BlockType) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *BlockType) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *BlockType) SetTypeName(v string) {
	x.xxx_hidden_TypeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *BlockType) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *BlockType) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BlockType) HasTypeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BlockType) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BlockType) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *BlockType) ClearTypeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TypeName = nil
}

func (x *BlockType) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

type BlockType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *int32
	TypeName    *string
	Description *string
}

func (b0 BlockType_builder) Build() *BlockType {
	m0 := &BlockType{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = *b.Id
	}
	if b.TypeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_TypeName = b.TypeName
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Description = b.Description
	}
	return m0
}

type GetBlockTypesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockTypesRequest) Reset() {
	*x = GetBlockTypesRequest{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTypesRequest) ProtoMessage() {}

func (x *GetBlockTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetBlockTypesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetBlockTypesRequest_builder) Build() *GetBlockTypesRequest {
	m0 := &GetBlockTypesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetBlockTypesResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockTypes *[]*BlockType          `protobuf:"bytes,1,rep,name=block_types,json=blockTypes"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetBlockTypesResponse) Reset() {
	*x = GetBlockTypesResponse{}
	mi := &file_internal_proto_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTypesResponse) ProtoMessage() {}

func (x *GetBlockTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBlockTypesResponse) GetBlockTypes() []*BlockType {
	if x != nil {
		if x.xxx_hidden_BlockTypes != nil {
			return *x.xxx_hidden_BlockTypes
		}
	}
	return nil
}

func (x *GetBlockTypesResponse) SetBlockTypes(v []*BlockType) {
	x.xxx_hidden_BlockTypes = &v
}

type GetBlockTypesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockTypes []*BlockType
}

func (b0 GetBlockTypesResponse_builder) Build() *GetBlockTypesResponse {
	m0 := &GetBlockTypesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BlockTypes = &b.BlockTypes
	return m0
}

var File_internal_proto_storage_storage_proto protoreflect.FileDescriptor

const file_internal_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/storage/storage.proto\x12\astorage\"4\n" +
	"\x15ListDataBlocksRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xdf\x01\n" +
	"\tDataBlock\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x05R\ablockId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vchiphertext\x18\x03 \x01(\fR\vchiphertext\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12-\n" +
	"\aprofile\x18\x06 \x01(\x0e2\x13.storage.EncProfileR\aprofile\x12&\n" +
	"\x04type\x18\a \x01(\v2\x12.storage.BlockTypeR\x04type\"\xc0\x01\n" +
	"\x14SaveDataBlockRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vchiphertext\x18\x02 \x01(\fR\vchiphertext\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12-\n" +
	"\aprofile\x18\x05 \x01(\x0e2\x13.storage.EncProfileR\aprofile\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\x05R\x06typeId\"\x17\n" +
	"\x15SaveDataBlockResponse\"M\n" +
	"\x16ListDataBlocksResponse\x123\n" +
	"\vdata_blocks\x18\x01 \x03(\v2\x12.storage.DataBlockR\n" +
	"dataBlocks\"Z\n" +
	"\tBlockType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x16\n" +
	"\x14GetBlockTypesRequest\"L\n" +
	"\x15GetBlockTypesResponse\x123\n" +
	"\vblock_types\x18\x01 \x03(\v2\x12.storage.BlockTypeR\n" +
	"blockTypes*<\n" +
	"\n" +
	"EncProfile\x12\x0e\n" +
	"\n" +
	"PROFILE_V1\x10\x00\x12\x0e\n" +
	"\n" +
	"PROFILE_V2\x10\x01\x12\x0e\n" +
	"\n" +
	"PROFILE_V3\x10\x022\x86\x02\n" +
	"\x0eStorageService\x12N\n" +
	"\rSaveDataBlock\x12\x1d.storage.SaveDataBlockRequest\x1a\x1e.storage.SaveDataBlockResponse\x12S\n" +
	"\x0eListDataBlocks\x12\x1e.storage.ListDataBlocksRequest\x1a\x1f.storage.ListDataBlocksResponse0\x01\x12O\n" +
	"\x0eListBlockTypes\x12\x1d.storage.GetBlockTypesRequest\x1a\x1e.storage.GetBlockTypesResponseB\x18Z\x16internal/proto/storageb\beditionsp\xe9\a"

var file_internal_proto_storage_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_storage_storage_proto_goTypes = []any{
	(EncProfile)(0),                // 0: storage.EncProfile
	(*ListDataBlocksRequest)(nil),  // 1: storage.ListDataBlocksRequest
	(*DataBlock)(nil),              // 2: storage.DataBlock
	(*SaveDataBlockRequest)(nil),   // 3: storage.SaveDataBlockRequest
	(*SaveDataBlockResponse)(nil),  // 4: storage.SaveDataBlockResponse
	(*ListDataBlocksResponse)(nil), // 5: storage.ListDataBlocksResponse
	(*BlockType)(nil),              // 6: storage.BlockType
	(*GetBlockTypesRequest)(nil),   // 7: storage.GetBlockTypesRequest
	(*GetBlockTypesResponse)(nil),  // 8: storage.GetBlockTypesResponse
}
var file_internal_proto_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.DataBlock.profile:type_name -> storage.EncProfile
	6, // 1: storage.DataBlock.type:type_name -> storage.BlockType
	0, // 2: storage.SaveDataBlockRequest.profile:type_name -> storage.EncProfile
	2, // 3: storage.ListDataBlocksResponse.data_blocks:type_name -> storage.DataBlock
	6, // 4: storage.GetBlockTypesResponse.block_types:type_name -> storage.BlockType
	3, // 5: storage.StorageService.SaveDataBlock:input_type -> storage.SaveDataBlockRequest
	1, // 6: storage.StorageService.ListDataBlocks:input_type -> storage.ListDataBlocksRequest
	7, // 7: storage.StorageService.ListBlockTypes:input_type -> storage.GetBlockTypesRequest
	4, // 8: storage.StorageService.SaveDataBlock:output_type -> storage.SaveDataBlockResponse
	5, // 9: storage.StorageService.ListDataBlocks:output_type -> storage.ListDataBlocksResponse
	8, // 10: storage.StorageService.ListBlockTypes:output_type -> storage.GetBlockTypesResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_storage_storage_proto_init() }
func file_internal_proto_storage_storage_proto_init() {
	if File_internal_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_storage_storage_proto_rawDesc), len(file_internal_proto_storage_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_internal_proto_storage_storage_proto_depIdxs,
		EnumInfos:         file_internal_proto_storage_storage_proto_enumTypes,
		MessageInfos:      file_internal_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_internal_proto_storage_storage_proto = out.File
	file_internal_proto_storage_storage_proto_goTypes = nil
	file_internal_proto_storage_storage_proto_depIdxs = nil
}
