// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: internal/proto/storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_SaveDataBlock_FullMethodName  = "/storage.StorageService/SaveDataBlock"
	StorageService_ListDataBlocks_FullMethodName = "/storage.StorageService/ListDataBlocks"
	StorageService_ListBlockTypes_FullMethodName = "/storage.StorageService/ListBlockTypes"
	StorageService_Ping_FullMethodName           = "/storage.StorageService/Ping"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService manages user storage and private keys.
type StorageServiceClient interface {
	// SaveDataBlock saves a data block with encrypted payload for the user.
	SaveDataBlock(ctx context.Context, in *SaveDataBlockRequest, opts ...grpc.CallOption) (*SaveDataBlockResponse, error)
	// ListDataBlocks returns a list of data blocks stored for the user with encrypted payload.
	ListDataBlocks(ctx context.Context, in *ListDataBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDataBlocksResponse], error)
	// ListBlockTypes returns a list of available block types.
	ListBlockTypes(ctx context.Context, in *GetBlockTypesRequest, opts ...grpc.CallOption) (*GetBlockTypesResponse, error)
	// Ping checks the connectivity with the storage service.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) SaveDataBlock(ctx context.Context, in *SaveDataBlockRequest, opts ...grpc.CallOption) (*SaveDataBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDataBlockResponse)
	err := c.cc.Invoke(ctx, StorageService_SaveDataBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListDataBlocks(ctx context.Context, in *ListDataBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListDataBlocksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_ListDataBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListDataBlocksRequest, ListDataBlocksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListDataBlocksClient = grpc.ServerStreamingClient[ListDataBlocksResponse]

func (c *storageServiceClient) ListBlockTypes(ctx context.Context, in *GetBlockTypesRequest, opts ...grpc.CallOption) (*GetBlockTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockTypesResponse)
	err := c.cc.Invoke(ctx, StorageService_ListBlockTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StorageService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService manages user storage and private keys.
type StorageServiceServer interface {
	// SaveDataBlock saves a data block with encrypted payload for the user.
	SaveDataBlock(context.Context, *SaveDataBlockRequest) (*SaveDataBlockResponse, error)
	// ListDataBlocks returns a list of data blocks stored for the user with encrypted payload.
	ListDataBlocks(*ListDataBlocksRequest, grpc.ServerStreamingServer[ListDataBlocksResponse]) error
	// ListBlockTypes returns a list of available block types.
	ListBlockTypes(context.Context, *GetBlockTypesRequest) (*GetBlockTypesResponse, error)
	// Ping checks the connectivity with the storage service.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) SaveDataBlock(context.Context, *SaveDataBlockRequest) (*SaveDataBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDataBlock not implemented")
}
func (UnimplementedStorageServiceServer) ListDataBlocks(*ListDataBlocksRequest, grpc.ServerStreamingServer[ListDataBlocksResponse]) error {
	return status.Error(codes.Unimplemented, "method ListDataBlocks not implemented")
}
func (UnimplementedStorageServiceServer) ListBlockTypes(context.Context, *GetBlockTypesRequest) (*GetBlockTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockTypes not implemented")
}
func (UnimplementedStorageServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_SaveDataBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDataBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SaveDataBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SaveDataBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SaveDataBlock(ctx, req.(*SaveDataBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListDataBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDataBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ListDataBlocks(m, &grpc.GenericServerStream[ListDataBlocksRequest, ListDataBlocksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ListDataBlocksServer = grpc.ServerStreamingServer[ListDataBlocksResponse]

func _StorageService_ListBlockTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListBlockTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListBlockTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListBlockTypes(ctx, req.(*GetBlockTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveDataBlock",
			Handler:    _StorageService_SaveDataBlock_Handler,
		},
		{
			MethodName: "ListBlockTypes",
			Handler:    _StorageService_ListBlockTypes_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StorageService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDataBlocks",
			Handler:       _StorageService_ListDataBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/storage/storage.proto",
}
